site: 'http://enceladus:3000'
user: 'corcoran-admin@twistage.com'
password: 'Testing1'
company: 'corcoran'
license_key: '8fac72ba79155'
album_id: 'm283d7494e952'
image_id: 'i1f38c17cedea'
#track_id: 't86aa451e2aa1' # FIXME
video_id: 'ad993f8407534'
