# site: 'http://service-staging.twistage.com'#http://service-staging.twistage.com'
# license_key: '993693f2d9a6b' #staging new city'e4ae509a20e8a' #staging basher'993693f2d9a6b' #localcorc c5dc8a2e9be75
# company: 'api-basher'
# video_id: 'e1ec162703eff'
# album_id: 'mea3bdee751a7'
# library_id: 'default'

site: 'http://service-staging.twistage.com'
license_key: '993693f2d9a6b'#993693f2d9a6b'#17441ffae76a5
company: 'api-basher'
video_id: 'e1ec162703eff'
album_id: 'mea3bdee751a7'
library_id: 'development'

# site: 'http://jsmith:3000'
# license_key: 'c5dc8a2e9be75'
# company: 'corcoran'
# video_id: '239c59483d346'
# album_id: 'm2267d16c16e6'
# library_id: 'default'